// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7L4LUoCa_WQPvV6et_Yqwe6NuFUlDNGI',
    appId: '1:959623116610:web:b4226d445d93c61344badb',
    messagingSenderId: '959623116610',
    projectId: 'nadilk',
    authDomain: 'nadilk.firebaseapp.com',
    storageBucket: 'nadilk.appspot.com',
    measurementId: 'G-RXTG7F3M3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfPNKs-toRt9zvuACgy1iBjFiin65H0uM',
    appId: '1:959623116610:android:16641160661154ab44badb',
    messagingSenderId: '959623116610',
    projectId: 'nadilk',
    storageBucket: 'nadilk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTd9gSnJpxhPVHyktGmJ1PUiSkU4DMDWI',
    appId: '1:959623116610:ios:1081bd166ef314a044badb',
    messagingSenderId: '959623116610',
    projectId: 'nadilk',
    storageBucket: 'nadilk.appspot.com',
    iosClientId: '959623116610-2vrjrd3b2sphtdurqf9qdrf8n1gq8rcl.apps.googleusercontent.com',
    iosBundleId: 'com.example.nudilk',
  );
}
